import re
import json
from pathlib import Path

WORLD_FILE_PATH = (
    Path(__file__).resolve().parents[1] / "webots" / "worlds" / "map_v3.wbt"
)
OUTPUT_FILE_PATH = Path(__file__).resolve().parent / "map_data.py"


def parse_world_file(content: str):
    junction_coords = {}
    global_graph = {}
    path_details = {}
    road_count = 0

    crossroad_re = re.compile(
        r'Crossroad\s*\{[^}]*?translation\s+([\-\d.]+)\s+([\-\d.]+)\s+[\-\d.]+[^}]*?id\s+"(.*?)"',
        re.DOTALL,
    )
    for m in crossroad_re.finditer(content):
        x, y, jid = m.groups()
        junction_coords[jid] = (float(x), float(y))
        global_graph.setdefault(jid, [])

    road_starts = [m.start() for m in re.finditer(r"\bRoad\s*\{", content)]

    def extract_block(s, i):
        if i >= len(s) or s[i] != "{":
            return None, i
        depth = 0
        start = i
        while i < len(s):
            if s[i] == "{":
                depth += 1
            elif s[i] == "}":
                depth -= 1
                if depth == 0:
                    return s[start + 1 : i], i + 1
            i += 1
        return None, i

    waypoint_re = re.compile(r"([\-\d.]+)\s+([\-\d.]+)\s+[\-\d.]+")

    for rs in road_starts:
        brace = content.find("{", rs)
        if brace == -1:
            continue
        block, _ = extract_block(content, brace)
        if not block:
            continue

        road_count += 1

        trans = re.search(r"translation\s+([\-\d.]+)\s+([\-\d.]+)\s+[\-\d.]+", block)
        if not trans:
            continue
        base_x, base_y = map(float, trans.groups())

        sm = re.search(r'startJunction\s+"(.*?)"', block)
        em = re.search(r'endJunction\s+"(.*?)"', block)
        wps = re.search(r"wayPoints\s*\[\s*(.*?)\s*\]", block, re.DOTALL)
        if not sm:
            continue
        start_id = sm.group(1)
        end_id = em.group(1) if em else ""
        wp_str = wps.group(1) if wps else ""

        if start_id in junction_coords and end_id and end_id in junction_coords:
            if end_id not in global_graph[start_id]:
                global_graph[start_id].append(end_id)
            if start_id not in global_graph[end_id]:
                global_graph[end_id].append(start_id)

        abs_wps = []
        for w in waypoint_re.finditer(wp_str):
            wx, wy = map(float, w.groups())
            abs_wps.append((round(base_x + wx, 3), round(base_y + wy, 3)))

        path_details[(start_id, end_id)] = abs_wps
        if end_id:
            path_details[(end_id, start_id)] = abs_wps[::-1]

    return junction_coords, global_graph, path_details, road_count


def write_output_file(path, junction_coords, global_graph, path_details):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by parse_world.py\n")
        f.write("import json\n\n")
        f.write("JUNCTION_COORDS = ")
        f.write(json.dumps(junction_coords, indent=2))
        f.write("\n\nGLOBAL_GRAPH = ")
        f.write(json.dumps(global_graph, indent=2))
        f.write("\n\nPATH_DETAILS = {\n")
        for (s, e), pts in path_details.items():
            f.write(f"  ({json.dumps(s)}, {json.dumps(e)}): {json.dumps(pts)},\n")
        f.write("}\n")


def main():
    try:
        content = Path(WORLD_FILE_PATH).read_text(encoding="utf-8")
    except FileNotFoundError:
        print(f"ERROR: World file not found: {WORLD_FILE_PATH}")
        return

    junction_coords, global_graph, path_details, road_count = parse_world_file(content)
    if not junction_coords or not global_graph:
        print("ERROR: No data extracted from world file.")
        return

    write_output_file(OUTPUT_FILE_PATH, junction_coords, global_graph, path_details)

    print("Found in world file:")
    print(f"  Crossroads: {len(junction_coords)}")
    print(f"  Roads: {road_count}")
    print(f"Data written to: {OUTPUT_FILE_PATH}")


if __name__ == "__main__":
    main()
